.travis.yml
This commit disables continuous deploys
cc @wslack
=> Disable continuous deploys

nginx.conf
and also split that line into multiple lines for easier reading
=> add font mimetypes to gzip compression list

nginx.conf
ref https://github.com/18F/federalist-proxy/issues/19
=> Add text/html type for cfm extension

nginx.conf
=> Update comments in nginx.conf

manifest.yml, nginx.conf, staging_manifest.yml
Reverts 18F/federalist-proxy#24
ref #26
=> Revert "Add CORS support for GET requests from s.codepen.io"

README.md, bin/parse-conf.js, docker-compose.yml, manifest.yml, nginx.conf, staging_manifest.yml, test/main.js
Update HTST headers to `includeSubDomains` to support cloud.gov site.
=> Update HSTS headers

README.md, bin/parse-conf.js, docker-compose.yml, manifest.yml, nginx.conf, test/main.js
=> Configures additional subdomains to receive `includeSubdomains` in HSTS header

README.md, bin/parse-conf.js, docker-compose.yml, manifest.yml, nginx.conf, test/main.js
Add more domains to receive `includeSubDomains` in HSTS header.
=> Release 20200623

nginx.conf, test/main.js
add header x-server: federalist
=> add x-server header to https response

.circleci/config.yml, bin/parse-conf.js
=> Release 2020-07-14

.circleci/config.yml, bin/parse-conf.js
=> Release 2020-07-17

.cloudgov/manifest.yml
=> Add login.gov subdomain to INCLUDE_SUBDOMAINS

.circleci/config.yml, bin/parse-conf.js
- add login.gov to sites receiving `includeSubDomains` in HSTS header
- update deps
=> Release 2020-09-14

ci/pipeline.yml, ci/vars/example.yml
Fixes issue(s) 18F/federalist#3454.
Proposed changes in this pull request:
- leverage Credhub for concourse variables
=> Migrate variables to credhub and remove commented out config

.circleci/config.yml, .cloudgov/vars/pages-staging.yml, ci/pipeline.yml, ci/tasks/deploy.sh
- Restore Federalist staging to Circle
- migrate Pages staging in Concourse
- add pages-staging space
=>  Support pages-staging space and restore Federalist staging to Circle

.github/workflows/security-considerations.yml
Add security-considerations-action
Add security-considerations-action
=> Add security-considerations-action

.cloudgov/manifest.yml, bin/mock.js, bin/parse-conf.js, docker-compose.yml, nginx.conf, package.json, test/main.js
=> Replace S3 bucket website config, use fips endpoints, update tests/mock

buildpack.yml
=> Configure nginx buildpack for openresty

.circleci/config.yml, bin/mock.js, ci/pipeline.yml, docker-compose.yml, nginx.conf, package.json, test/fixtures.js, test/integrationTestsHooks.js, test/main.js
- Fixes timing issue when setting up buckets for integration tests by actually waiting
- Fixes s3 redirect configuration
- Always returns default site 404 to match current behavior
- Adds additional tests for default and preview paths
- Adds additional tests for updated 404 handling
- Refactors tests
None
=> Fixes and refactoring 

bin/mock.js, nginx.conf, test/fixtures.js, test/main.js
Finally address the issue I was seeing!
- Handle paths with periods
- Additional tests
None
=> Handle paths with periods!

nginx.conf, test/main.js
Reverts 18F/federalist-proxy#124
=> Revert "Release - 2022-01-24"

nginx.conf, test/main.js
Reverts 18F/federalist-proxy#127
None
=> Revert "Revert 124 staging"

nginx.conf, test/main.js
- #121 
- Return relative redirects for bare paths
None
=> found the magical incantation for relative redirects!

nginx.conf, test/fixtures.js, test/main.js
- #130 
- Removes special logic for .cfm files
-
None
=> remove special handling of cfm files

nginx.conf
- Adds actual app logging to the proxy
This currently doesn't add any information not already surfaced from the CF router logs, BUT now it works and we can add more detail as we see fit.
None
=> See app logs on CG

docker-compose.yml
- Debugging? Tests are failing only in CI for unknown reason
None
=> Update volume for robots

docker-compose.yml, nginx.conf, test/main.js
- Handle backslashes in paths
yes
=> Release 2022-02-04

docker-compose.yml, nginx.conf, public/robots.txt, test/main.js
- Use X-Robots-Tag https://github.com/18F/federalist-proxy/pull/145
Noted in https://github.com/18F/federalist-proxy/pull/145
=> Proxy Release 2022-02-24

.cloudgov/manifest.yml
- Add `includeSubdomains` to the HSTS header for data.gov
None
=> Add includesubdomains to datagov

docker-compose.yml, nginx.conf, public/robots.txt, test/main.js
- Remove default robots.txt #111 
- Prevent indexing for preview urls #111 
- Add `includeSubdomains` for data.gov
None
=> Release 2022-03-08

.circleci/config.yml, .cloudgov/manifest.yml, ci/pipeline.yml
- Resolves #142 
- Remove @ing federalist operators in slack from Concourse
None
=> Release CI changes

.cloudgov/vars/production.yml
- Adjust memory based on [#3833 ](https://github.com/18F/federalist/issues/3833)
None
=> Adjust memory for apps

.cloudgov/vars/pages-production.yml, ci/pipeline.yml
- Add pages production depoloyments to Concourse CI
- Add pages .cloudgov deployment vars file
Needed for Pages SCR migration
=> Add pages production concourse jobs and cg vars file

docker-compose.yml, nginx.conf, public/robots.txt, test/main.js
- Update dependencies for testing
- Add codeql scaning
- Add deployment for Pages production to Concourse CI
- Remove Federalist staging from CircleCI
Update deps and needed for SCR completion.
=> Release 2022-07-22 

README.md, ci/pipeline.yml
- Refactors ci pipeline to use instanced pipelines
- Add self setting pipeline task to set pipeline on update to staging or main branch
- Add deploy docs in README
None
=> Update proxy pipeline to staging and production instanced pipelines

README.md
- Quick README ci link fix prior to staging merge
None
=> fix ci links in README

ci/federalist-pipeline.yml
- Fix set-pipeline job for federalist-proxy deployment #166 
- None
=> Release 08-03-2022

nginx.conf
- unset `x-amz-security-token` header
Changes to accepted headers across all sites
=> unset x-amz-security-token header

ci/federalist-pipeline.yml, ci/pipeline.yml
- fix: CI pipeline has working build-redirects task
None
=> fix: CI pipeline has working build-redirects task

nginx.conf
- fixes the regex for the additional encoded values check
- Tested against staging
fixes the regex for the additional encoded values check.
=> fix: Added encoded values check regex

nginx.conf, test/fixtures.js, test/main.js
- Update regex for encoded backslash check
Re: #185
=> update encoded backslash match, partial update of tests

.cloudgov/vars/pages-dev.yml, README.md, ci/federalist-pipeline.yml, ci/pipeline-dev.yml, ci/pipeline.yml, docker-compose.yml, package-lock.json, package.json
Related to [#4106](https://github.com/cloud-gov/pages-core/issues/4106) and [#3947 ](https://github.com/cloud-gov/pages-core/issues/3947)
- Add new `pipeline-dev.yml` for dev env deployment
- Deploys to dev space in CF org
Adds additional environment for improved developer experience and testing
=> feat: Add dev deployment env for PRs to staging

ci/federalist-pipeline.yml, ci/pipeline.yml
Related to https://github.com/cloud-gov/product/issues/2480
- Add commit verification of GPG keys
- Add commit verification of GPG keys
=> ci: Verify git commits with gpg keys

ci/partials/test-integrations.yml, ci/partials/test-mocks.yml, ci/pipeline-dev.yml, ci/pipeline.yml
Related to #201
- Create CI partials for test tasks
- Add git hardened resource type
Add hardened git resource
=> chore: Partialize CI tests and use hardened git resource

ci/partials/build-redirects.yml, ci/partials/cancel-deployment.yml, ci/partials/deploy.yml, ci/partials/restage.yml, ci/pipeline-dev.yml, ci/pipeline.yml
- Towards https://github.com/cloud-gov/pages-core/issues/4432
Adds additional hardened registry images
=> Container hardening

ci/partials/test-integrations.yml, ci/partials/test-mocks.yml, ci/pipeline-dev.yml, ci/pipeline.yml, docker-compose.yml
- Use hardened nginx image
Uses a hardened image for nginx.
=> Use hardened nginx image

ci/pipeline.yml
- Cleanup src pull to remove git depth
- Set to pull tags v1.x.x for production
None
=> chore: pull full repo for release

package-lock.json
- Ran `npm audit fix` to update node.js deps braces and fill-range
Updates security impacted dependencies
=> chore: Update node.js dependencies braces and fill-range

ci/pipeline.yml
- Fix CI task config to wait on other passing tasks before running release task
None
=> fix(ci): Set src passed at correct level for release tasks
