cloud-gov/pages-proxy

- manifest.yml
This commit scales the number of instances of the proxy running from 1 to 2. In the [cloud.gov production ready guide](https://cloud.gov/docs/apps/production-ready/) this is described as necessary to keep the app from going down during regular maintanence.
> Scale the number of instances up to 2

- manifest.yml
[The Staticfile Buildpack docs](http://docs.cloudfoundry.org/buildpacks/staticfile/#memory) suggest that apps using the buildpack use 64MB of RAM. We are currently using 512MB. This commit sets the amount of RAM per instance to the suggested level, and cranks up the instance count.
> Reduce instance memory from 512MB to 64MB

- nginx.conf
S3 redirects paths without a trailing slash to the same path with a trailing slack. For example `/site/18f/18f.gsa.gov/blog` redirects to `/site/18f/18f.gsa.gov/blog/`.
The problem is that this redirect is then forwarded to the client through Cloudfront. So a request for `18f.gsa.gov/blog` redirects to `18f.gsa.gov/site/18f/18f.gsa.gov/blog/`.
This commit fixes that problem by adding a `proxy_redirect` rule to remove the first 3 components in the path for a redirect.
> Add proxy_redirect rule to remove /site/org/repo component of URLs

- nginx.conf
This commit adds a `proxy_redirect` rule for preview URLs that works the same as the rule for published site URLs. Previously preview URLs could be ignored because they were not proxied, but we expect them to be with the coming "beta domain" feature.
> Set redirects for preview URLs

- manifest.yml
The federalist-proxy fields a large amount of traffic and as such needs to be deployed with autopilot. For this to work, environment variables need to be specified in either the manifest or a user provided service.
This commit adds the S3 bucket url to the manifest so that it doesn't need to be re-added every time we redeploy the proxy
> Add the S3 bucket url to the env in the manifest

- Dockerfile
- README.md
- docker-compose.yml
- manifest.yml
- nginx.conf
- staging_manifest.yml
This commit adds a Dockerfile and a Docker Compose configuration which can be used to run the app locally. The app will run as if it were running in the staging environment
As part of the above change, the app also adds a staging manifest so the app's staging configuration can be described.
> Setup Docker so the proxy can run locally

- nginx.conf
This commit changes the proxy so that requests with the prefix `/demo/<org>/<repo>` trim the `/demo/<org>/<repo>` element from redirects. For requests with the prefix `/prefix/<org>/<repo>/<branch>`, it quits trimming the prefix.
This is necessary now that demo branches are published in `/demo` instead of `/preview`.
> Swap proxy redirects for /preview and /demo

- nginx.conf
- robots.txt
This commit adds a robots.txt file that is served at `/robots.txt`. This will prevent the site from being crawled and content from showing up in search engines at the proxy instead of the published site.
> Add robots.txt

- nginx.conf
I added all of the font mimetypes from Cloudflare's list of gzipped file types over at https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-gzip-
> Enable gzip for more font mimetypes

- nginx.conf
After https://github.com/18F/federalist-garden-build/pull/47 the build container started creating redirect objects for the site. A result of this is that we no longer need to strip the baseurl out of demo and site paths since the BASEURL will handle that when the build is run.
This commit removes the proxy_redirect rules that strip the baseurl out of demo and site paths.
> Remove proxy_redirect rules

- nginx.conf
ref #19
To figure out and test this solution, since the previous attempt in #20 didn't work, I setup an instance of the proxy in my cloud.gov sandbox. It also points to the Federalist staging bucket.
* sandbox `.cfm` url, **works**: https://federalist-proxy-sandbox.app.cloud.gov/site/gsa/plainlanguage.gov/plLaw/index.cfm
* staging `.cfm` url, **doesn't work** currently: https://federalist-proxy-staging.app.cloud.gov/site/gsa/plainlanguage.gov/plLaw/index.cfm
> add text/html content-type to .cfm locations

- manifest.yml
- nginx.conf
- staging_manifest.yml
Based on example at https://enable-cors.org/server_nginx.html
I tested this by launching an instance of this proxy in my cloud.gov sandbox and trying it on codepen: https://codepen.io/anon/pen/zRKdaM?editors=1111
Also, I updated this app's CloudFoundry manifest files to adhere to the new format (basically just nested under an `applications` key). Ref http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated.
> Add CORS support for GET requests from s.codepen.io

- manifest.yml
- staging_manifest.yml
Basically just nest everything under an `applications:` key. No functional changes, but the old version will be deprecated at some point in the future so this just gets us ready for that. See http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated
ref #28.
> Use new manifest file format

- manifest.yml
- nginx.conf
- staging_manifest.yml
Updated federalist proxy to use the subdomain name from requests ie(`<name>.app.cloud.gov`) to either route requests to the shared bucket when coming from `https://federalist-proxy.app.cloud.gov` or to the private bucket when coming from a route `https://<bucket-name>.app.cloud.gov`
> Route requests to bucket based on subdomain

- nginx.conf
GSA to comply with Binding Operational Directive (BOD) 18-01
HSTS preloading is an opt in process in which the domain will be added to the preload lists for various browsers. These lists are hard coded within the various browsers (Chrome, IE, Firefox) and are used to further enforce HTTPS only for the domain. This in turn will provide enhanced security for any clients that connect to the aforementioned domain.. 
Remaining requirements to qualify for preload are listed below as indicated by https://hstspreload.org/ :
Examine all subdomains (and nested subdomains) of your site and make sure that they work properly over HTTPS  
Include the preload flag within the domains HSTS header.
Example:  max-age=63072000; includeSubDomains; preload
> increase memory and add preload directive to hsts header

- manifest.yml
- nginx.conf
- staging_manifest.yml
Cloud Foundry recommends using an http health check when possible. This will be a better indication of whether or not the application is ready to serve requests.
Add `access_log off;` since we don't need these requests to clog up the logs.
> Add and configure http health check endpoint

- .circleci/config.yml
- .cloudgov/deploy.sh
- README.md
Looks like there were issues installing the CF CLI in our deployment pipelines. Here I attempt to update this according to the latest docs. If this is 💯 then will do the same in other repos.
> Update installation of cf in Circle and use `cf` command

- .cloudgov/manifest.yml
- bin/parse-conf.js
- docker-compose.yml
- nginx.conf
- remove `PROXY_SSL_VERIFY`
This removes this setting from nginx. It isn't necessary to proxy over https and requires the explicit installation of certs from the upstream.
SSL still in effect.
> remove proxy_ssl_verify

- nginx.conf
- Conditional headers are forwarded by cloudfront but not part of the cache key so we get cached responses that don't make sense for future requests. Drop them here, so our cache stays valid
None
> drop conditional headers on proxied calls

- bin/mock.js
- docker-compose.yml
- nginx.conf
- package.json
- test/fixtures.js
- test/integrationTestsHooks.js
- test/main.js
- Returns the actual 404.html in the build context (site/demo/preview) root
- Updates tests to use prefix paths and consolidate some stuff
-
None
> Update tests and return correct 404

- nginx.conf
- test/main.js
- returns a 301 to `/foo/` for all `/foo`
- Addresses #121 
None
> 301 Redirect all /foo to /foo/

- nginx.conf
- test/main.js
- Addresses #121 
- Explicitly redirects using https
This is necessary bc nginx always prepends `$scheme://$host` to any relative path so we have to set it explicitly.
None
> Explicitly redirect to https and a little refactoring

- nginx.conf
- test/main.js
- redirects based on user agent header (if Amazon Cloudfront)
- #121 
None -  but it is a string comparison and redirects are relative only
> set redirect path based on user agent header

- nginx.conf
- test/main.js
- Returns 404s if backslashes exist in certain parts of the path
yes
> Return 404s for backslashes at site root or after

- .circleci/config.yml
- Explicitly set CircleCI image to use Ubuntu 20.04
to address the need documented in #142 (whoops; I typoed my branch name 😬).
This change is necessary because CircleCI has deprecated the default Ubuntu 14.04 image and it will stop working after May 2021. Because we were setting
```yml
machine: true
```
we were getting that default. I have changed this to
```yml
machine:
image: image: ubuntu-2004:202201-02
```
in accordance with CircleCI's migration documentation, which is at
https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/
None
> Explicitly set CircleCI image to use Ubuntu 20.04

- docker-compose.yml
- nginx.conf
- public/robots.txt
- test/main.js
Relates to https://github.com/18F/federalist-proxy/issues/111
- Remove static robots.txt file from being served
- Add `X-Robots-Tag` to non-Cloudfront requests based on User Agent
I believe that if someone were to modify their user agent they could potentially have a non-Cloudfront request served without the `X-Robots-Tag`, potentially making it indexable, however without tracking all of AWS's Cloudfront IPs the user agent appears to be the only other way to identify Cloudfront requests.
> Use X-Robots-Tag

- .circleci/config.yml
- Explicitly set CircleCI image to use Ubuntu 20.04 — just like I did in #143, but *this* time I also did it in the three CircleCI machines I missed.
to address the need documented in #142.
This change is necessary because CircleCI has deprecated the default Ubuntu 14.04 image and it will stop working after May 2021. Because we were setting
```yml
machine: true
```
we were getting that default. I have changed this to
```yml
machine:
image: image: ubuntu-2004:202201-02
```
in accordance with CircleCI's migration documentation, which is at
https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/
None
> Explicitly set the _rest_ of the CircleCI machines to use Ubuntu 20.04.

- ci/pipeline.yml
- Remove inclusion of slack-users variable in Concourse Slack job status messages
None
> Remove slack-users from Concourse job notifications

- nginx.conf
- Resolve cache poisoning
Omits x-amz-expected-bucket-owner from being passed to S3
> Add x-amz-expected-bucket-owner to the list of headers not passed to S3

- .cloudgov/manifest.yml
- Add the search.gov id to the includes subdomains environment variable in manifest.yml to add requested HSTS headers
- Add HSTS headers to search.gov
> Add includesubdomains to searchgov

- ci/federalist-pipeline.yml
- Fixed the set-pipeline task to set the pipeline for federalist-proxy and not the pages proxy pipeline.
None
> Fixed the set-pipeline job to federalist-proxy pipeline

- README.md
- bin/utils.js
- nginx.conf
- test/fixtures.js
- test/redirects.js
- Add `usePreviewPath` value in redirect object to keep the site preview path generated by the platform appended to the redirect
None
> feat: Add usePreviewPath option on redirects to keep site preview path on redirect

- nginx.conf
- test/main.js
Closes #187 
- Add header `Access-Control-Allow-Methods "GET, HEAD"`
- Return 405 Method Not Allowed response when trying HTTP methods that are not `GET` or `HEAD`
Adds additional restrictions to the methods allow against the proxy.
> feat: Only allow GET, HEAD requests

- ci/federalist-pipeline.yml
- ci/pipeline.yml
- ci/tasks/deploy.sh
Apart of https://github.com/cloud-gov/pages-core/issues/4054
- Explicitly set stack via the `--stack` flag in `cf push`
- Updates stack to run on cflinuxfs4 via `CF_STACK` param
Updates app to run on the latest base image: cflinuxfs4 stack (Ubuntu Jammy)
> chore: Update app stack to cflinuxfs4

- ci/federalist-pipeline.yml
- ci/pipeline.yml
Related to https://github.com/cloud-gov/pages-core/issues/4077
- Update cf-image to use hardened container image
This adds the hardened container to run CF tasks
> feat: Switch to using harden container for cf-image

- ci/pipeline-dev.yml
- ci/pipeline.yml
Related to https://github.com/cloud-gov/pages-core/issues/4394
- Switches to use the general-task image
- Adds registry-image resource type
Related to adding hardened containers
> chore(ci): Switch to general-task and registry-image for CI jobs

- .cz.json
- ci/pipeline.yml
- Rework CI task topology for staging and prod pipelines
- Add commitizen's `.cz.json` config for releases
None
> chore(ci): Rework staging and prod CI task topology and add .cz.json config
